import type { ResumeData } from "@/lib/types"

export const defaultResumeData: ResumeData = {
  personal: {
    name: "Jake Ryan",
    phone: "123-456-7890",
    email: "jake@su.edu",
    linkedin: "linkedin.com/in/jake",
    github: "github.com/jakeryan",
  },
  education: [
    {
      institution: "Southwestern University",
      location: "Georgetown, TX",
      degree: "Bachelor of Arts in Computer Science, Minor in Business",
      startDate: new Date("2018-08-01"),
      endDate: new Date("2021-05-01"),
      current: false,
    },
    {
      institution: "Blinn College",
      location: "Bryan, TX",
      degree: "Associate's in Liberal Arts",
      startDate: new Date("2014-08-01"),
      endDate: new Date("2018-05-01"),
      current: false,
    },
  ],
  experience: [
    {
      company: "Texas A&M University",
      position: "Undergraduate Research Assistant",
      location: "College Station, TX",
      startDate: new Date("2020-06-01"),
      current: true,
      description: [
        "Developed a REST API using FastAPI and PostgreSQL to store data from learning management systems",
        "Developed a full-stack web application using Flask, React, PostgreSQL and Docker to analyze GitHub data",
        "Explored ways to visualize GitHub collaboration in a classroom setting",
      ],
    },
    {
      company: "Southwestern University",
      position: "Information Technology Support Specialist",
      location: "Georgetown, TX",
      startDate: new Date("2018-09-01"),
      current: true,
      description: [
        "Communicate with managers to set up campus computers used on campus",
        "Assess and troubleshoot computer problems brought by students, faculty and staff",
        "Maintain upkeep of computers, classroom equipment, and 200 printers across campus",
      ],
    },
    {
      company: "Southwestern University",
      position: "Artificial Intelligence Research Assistant",
      location: "Georgetown, TX",
      startDate: new Date("2019-05-01"),
      endDate: new Date("2019-07-01"),
      current: false,
      description: [
        "Explored methods to generate video game dungeons based off of The Legend of Zelda",
        "Developed a game in Java to test the generated dungeons",
        "Contributed 50K+ lines of code to an established codebase via Git",
        "Conducted a human subject study to determine which video game dungeon generation technique is enjoyable",
        "Wrote an 8-page paper and gave multiple presentations on-campus",
        "Presented virtually to the World Conference on Computational Intelligence",
      ],
    },
  ],
  projects: [
    {
      name: "Gitlytics",
      startDate: new Date("2020-06-01"),
      current: true,
      description: ["", "", "", ""]
    },
    {
      name: "Simple Paintball",
      startDate: new Date("2018-05-01"),
      endDate: new Date("2020-05-01"),
      current: false,
      description: ["", "", "", ""]
    },
  ],
  skills: [
    { name: "Java", category: "languages" },
    { name: "Python", category: "languages" },
    { name: "C/C++", category: "languages" },
    { name: "SQL (Postgres)", category: "languages" },
    { name: "JavaScript", category: "languages" },
    { name: "HTML/CSS", category: "languages" },
    { name: "R", category: "languages" },
    { name: "React", category: "frameworks" },
    { name: "Node.js", category: "frameworks" },
    { name: "Flask", category: "frameworks" },
    { name: "JUnit", category: "frameworks" },
    { name: "WordPress", category: "frameworks" },
    { name: "Material-UI", category: "frameworks" },
    { name: "FastAPI", category: "frameworks" },
    { name: "Git", category: "developer_tools" },
    { name: "Docker", category: "developer_tools" },
    { name: "TravisCI", category: "developer_tools" },
    { name: "Google Cloud Platform", category: "developer_tools" },
    { name: "VS Code", category: "developer_tools" },
    { name: "Visual Studio", category: "developer_tools" },
    { name: "PyCharm", category: "developer_tools" },
    { name: "IntelliJ", category: "developer_tools" },
    { name: "Eclipse", category: "developer_tools" },
    { name: "pandas", category: "libraries" },
    { name: "NumPy", category: "libraries" },
    { name: "Matplotlib", category: "libraries" },
  ],
}

